export const GET_ALL_DISCUSS = "GET_ALL_DISCUSS";
export const GET_DISCUSS_BY_INDEX = "GET_DISCUSS_BY_INDEX";
export const POST_DISCUSS_QUESTION = "POST_DISCUSS_QUESTION";
export const POST_DISCUSS_COMMENT = "POST_DISCUSS_COMMENT";